AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smart-home-alexa-skill

  SAM Template for smart-home-alexa-skill
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tags:
      awsApplication: arn:aws:resource-groups:eu-west-1:584871003262:group/smart-home/03fm0jmhftcefu2v15rw1g0i1i

Resources:
  SmartHomeAlexaSkillFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Architectures:
        - arm64
      CodeUri: smart-home/
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          SQS_QUEUE_URL: !Ref SmartHomeMessageQueue
      Events:
        AlexaSkill:
          Type: AlexaSkill
          Properties:
            SkillId: amzn1.ask.skill.c4351ad6-6e70-415f-9463-12d54c1bb334
      Handler: app.lambdaHandler
      Policies: 
        - AWSLambdaBasicExecutionRole
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SmartHomeMessageQueue.QueueName
      Runtime: nodejs22.x
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  SmartHomeMessageQueue:
    Type: AWS::SQS::Queue
    Properties: 
      ContentBasedDeduplication: true
      FifoQueue: true
      Tags:
        - Key: awsApplication
          Value: arn:aws:resource-groups:eu-west-1:584871003262:group/smart-home/03fm0jmhftcefu2v15rw1g0i1i

Outputs:
  SmartHomeAlexaSkillFunction:
    Description: "Smart Home Alexa Skill Controller Function ARN"
    Value: !GetAtt SmartHomeAlexaSkillFunction.Arn
  SmartHomeAlexaSkillFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SmartHomeAlexaSkillFunction.Arn
  SmartHomeMessageQueue:
    Description: "Message Queue to interact with the Rpi"
    Value: !GetAtt SmartHomeMessageQueue.Arn
