service: home-control
frameworkVersion: "3"

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  sns-logger:
    handler: functions/sns-logger.handler
    events:
      - sns:
          arn: !Ref HomeEventTopic
          displayName: Home device event pipeline
          topicName: HomeEvent

resources:
  Resources:
    HomeEventTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: HomeEvent
