service: home-control
frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
