name: Build AWS-Connector Image

on:
  push:
    branches: [ "main" ]
    paths: 
      - aws-connector/
  workflow_dispatch:

env:
  GITHUB_USERNAME: pedroars99
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: $GITHUB_USERNAME
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./aws-connector
        file: ./aws-connector/Dockerfile
        push: true
        tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.GITHUB_USERNAME }}/aws-connector:latest
